name: Rakesh Deployment

# Trigger the action on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository's code
      - name: Checkout
        uses: actions/checkout@v2  # Checkout action (v2 is recommended)

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key ID
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key
          aws-region: us-east-1  # Set your AWS region

      # Step 3: Deploy static files to S3 bucket
      - name: Deploy static to S3 bucket
        run: aws s3 sync . s3://rakeshforum.com --delete  # Sync local directory to S3 with the --delete option
